export { BaseModel } from './BaseModel.js';
export { AppUser } from './AppUser.js';
export { Policy } from './Policy.js';
export type { PolicyConditions } from './Policy.js';
export { MagicToken } from './MagicToken.js';
export { AppSession } from './AppSession.js';
export { Grupo } from './Grupo.js';
export { Semana } from './Semana.js';
export { Actividad } from './Actividad.js';
export { IndicacionMalla } from './IndicacionMalla.js';
export { Competencia } from './Competencia.js';
export { ActividadEvaluacion } from './ActividadEvaluacion.js';
export { ActividadEvaluacionGrupo } from './ActividadEvaluacionGrupo.js';
export { PlanEvaluacion } from './PlanEvaluacion.js';
export type { PeriodoConfig } from './PlanEvaluacion.js';
export { ActividadEvaluacionAlumno } from './ActividadEvaluacionAlumno.js';
export { Equipo } from './Equipo.js';
export { GrupoAlumno } from './GrupoAlumno.js';
export { Entrevista } from './Entrevista.js';
export { EvaluacionEntrevista } from './EvaluacionEntrevista.js';
export { CompetenciaAlumno } from './CompetenciaAlumno.js';
export { Pagina } from './Pagina.js';
export type { ContentBlock } from './Pagina.js';
export { Etiqueta } from './Etiqueta.js';
// CMS "Contenidos" (design/cms-contenidos.html)
export { Coleccion } from './Coleccion.js';
export { Documento, DOCUMENTO_TIPOS, DOCUMENTO_PLANTILLAS } from './Documento.js';
export type { DocumentoTipo, DocumentoPlantilla } from './Documento.js';
export { DocumentoVersion } from './DocumentoVersion.js';
export { Recurso } from './Recurso.js';
// Módulo "Ejercicios" (mini-juez Kotlin/Swift)
export { EjercicioProgramacion, MODOS_EVALUACION, MARCADOR_SOLUCION } from './EjercicioProgramacion.js';
export type { CasoPrueba, CodigoInicial, CodigoPorLenguaje, ModoEvaluacion } from './EjercicioProgramacion.js';
export { EnvioEjercicio } from './EnvioEjercicio.js';
export type { DetalleCasoEnvio, EstadoEnvio } from './EnvioEjercicio.js';
export { CategoriaEjercicio } from './CategoriaEjercicio.js';
