// @ts-check
// Sidebar de la instancia de docs "tc2005b" (materia TC2005B).
// Autogenerado desde la estructura de carpetas de docs/tc2005b/.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
