// @ts-check
// Sidebar de la instancia de docs "tc2007b" (materia TC2007B).
// Autogenerado desde la estructura de carpetas de docs/tc2007b/.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
