@startuml mvc_secuencia
header MVC
autonumber
hide footbox

actor navegador
boundary routes
boundary "vista add.ejs" as vista_add
boundary "vista list.ejs" as vista_list
control controlador 
entity un_modelo 
entity Modelo

activate navegador
navegador -> routes: GET /add
deactivate navegador
activate routes
routes -> controlador: get_add(request, response)
deactivate routes
activate controlador
controlador -> vista_add: response.render('add.ejs')
deactivate controlador
activate vista_add
vista_add -> navegador: HTML
deactivate vista_add
activate navegador
navegador -> routes: POST /add
deactivate navegador
activate routes
routes -> controlador: post_add(request, response)
deactivate routes
activate controlador
controlador -> un_modelo **: new Modelo(request.body.valor)
activate un_modelo
controlador -> un_modelo: save()
deactivate un_modelo
controlador -> routes: response.redirect('/')
deactivate controlador
activate routes
routes -> controlador: get(request, response)
deactivate routes
activate controlador
controlador -> Modelo: fetchAll()
activate Modelo
Modelo -> controlador: objetos
deactivate Modelo
controlador -> vista_list: response.render('list.ejs', objetos)
deactivate controlador
activate vista_list
vista_list -> navegador: HTML
deactivate vista_list
activate navegador
deactivate navegador

@enduml